version: '3'
services:
  db:
    restart: always
    image: 'postgres:latest'
    environment:
      PSQL_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
     - ./server/pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  app:
    container_name: pokeapp-api
    restart: always
    build: ./server
    ports: 
      - "3000:3000"
    depends_on:
      - db

  client:
    container_name: pokeapp-client
    restart: always
    build: ./client
    ports:
      - "8080:8080" 
    depends_on:
      - app
