version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      PSQL_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
     - ./server/pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: pokeapp-api
    restart: always
    build: ./server
    ports: 
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: pokeapp-client
    restart: always
    build: ./client
    ports:
      - "8080:8080" 
    depends_on:
      - app
