version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      PSQL_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  app:
    container_name: pokeapp-api
    restart: always
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - db